### ISSUE TITLE
bug: Inaccurate arns added to IAM roles when using SSM parameters with .grant_read

### ISSUE THREAD

**Issue by m0llym0nster** [cdklabs/cdk-enterprise-iac#124]
### What is the problem?

I am attempting to add an ssm parameter that gets pulled by my EC2 instance in user-data via ` ssm_param.grant_read(ec2_role)`
The parameter arn being added to the iam policy is incorrect - having "CFN" prepended and random characters suffixed to the actual name of the parameter for the arn. The instance cannot access the parameter due to the incorrect arn being placed in its iam policy.

### Reproduction Steps

created a new simple stack for testing this one

create a new dir call it "resourceextractorbug" ; create a python cdk app inside of it `cdk init app --language=python`

replace app.py, your_stack.py, and requirements.txt from the attached zip file: [resourceextractorbug-12022022.zip](https://github.com/cdklabs/cdk-enterprise-iac/files/10142701/resourceextractorbug-12022022.zip)

activate venv & install deps:
```
source .venv/bin/activate
python3 -m pip install -r requirements.txt
```

deploy:
```
 npx cdk deploy ResourceExtractorBugPermissionsStack
 npx cdk deploy ResourceextractorbugStack
```

### What did you expect to happen?

Expected the arn for that ssm paramter to be added to the ec2 IAM role accurately, so that the instance can access the config.

### What actually happened?

incorrect arn was added to the IAM role - it had prepended text of CFN and random characters added at the suffix.

Example of arn added to Iam policy for that parameter: `"arn:aws:ssm:us-east-1:123456789:parameter/CFN-AmazonCloudWatchawsmollycandyC0C11414*"`

The actual actual arn for that parameter: `"arn:aws:ssm:us-east-1:123456789:parameter/AmazonCloudWatchawsmollycandy"`

### cdk-enterprise-iac version

0.0.97

### Language

Python

### Other information

cdk version 2.53.0

issue is in version cdk-enterprise-iac 0.0.94 to present.

Current workaround is to add the parameter to the inline policy when the role is created versus using .grant_read.

**Comment by maafk** [comment]
Thank you @m0llym0nster for opening this!

This pops up because you're providing an explicit `parameter_name` of `"AmazonCloudWatch-awsmolly-candy"`, which is [optional](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-parameter.html#cfn-ssm-parameter-name) in cloudformation (updated to this property requiring a [full replacement](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-replacement) of the resource). In general it's best practice to let Cloudformation choose a name for you in a situation like this to make stack updates easier in the future

Removing the `parameter_name` should yield an appropriate ARN.

Do you have any set requirements within your enterprise for explicit naming of SSM parameters?
